on:
  push:
    branches: main
  pull_request:

name: R-unit-testing.yaml

permissions: read-all

jobs:
  R-unit-testing:
    runs-on: windows-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install H3 manually
        run: Rscript -e 'source("tests/install_H3.R")'

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Run unit tests
        run: Rscript -e 'source("tests/testthat.R")'